# Generated by Django 3.2.12 on 2022-04-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(related_name='course_list', to='api.Subject'),
        ),
    ]
