# Generated by Django 3.2.12 on 2022-04-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_course_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subject',
            new_name='subjects',
        ),
    ]
